# Parallel ES/EN content intentionally repeats its schema, not executable logic.
# Keep security and reliability analysis enabled for both content files.
sonar.cpd.exclusions=src/i18n.ts,src/data/experience.ts
